global:
  scrape_interval: 5s  # Default scrape interval

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:9090' ]  # Target is the service name in Docker Compose
